In [1]:
import numpy as np
scores = np.array([[85, 90, 78, 92, 88],
                    [72, 75, 80, 68, 74],
                    [95, 88, 92, 96, 90,],
                    [60, 65, 70, 58, 62],  
                    [88, 84, 86, 89, 87]])

In [2]:
student=scores[2,:]
print("Student Score ",student)

Student Score  [95 88 92 96 90]


In [3]:
student=scores[:,1]
print("Student Score", student)

Student Score [90 75 88 65 84]


In [4]:
student=scores[:3,:2]
print("student scores",student)

student scores [[85 90]
 [72 75]
 [95 88]]


In [5]:
student=scores[3:,2:]
print("Student Scores" ,student)

Student Scores [[70 58 62]
 [86 89 87]]


In [6]:
Bonus_marks=scores + 5
print("Scores with bonus marks:",Bonus_marks)

Scores with bonus marks: [[ 90  95  83  97  93]
 [ 77  80  85  73  79]
 [100  93  97 101  95]
 [ 65  70  75  63  67]
 [ 93  89  91  94  92]]


In [7]:
sub_score=scores[:,3]-10
print("Subject score",sub_score)

Subject score [82 58 86 48 79]


In [8]:
total_marks=scores.sum(axis=1)
percentages=(total_marks/500) * 100
print("perentages scores",percentages)

perentages scores [86.6 73.8 92.2 63.  86.8]


In [9]:
student_marks=scores.mean(axis=1)
print("Average score per student",student_marks)

Average score per student [86.6 73.8 92.2 63.  86.8]


In [10]:
total_marks=scores.sum(axis=1)
print("student marks",total_marks)

student marks [433 369 461 315 434]


In [11]:
highest_score = scores.max()
print("Highest score :",highest_score)

Highest score : 96


In [12]:
average_scores_subject = scores.mean(axis=0)
print("Average score subject:", average_scores_subject)


Average score subject: [80.  80.4 81.2 80.6 80.2]


In [13]:
lowest_average_score_index = np.argmin(average_scores_subject)
print("Student with the lowest average score: Student", lowest_average_score_index + 1)

Student with the lowest average score: Student 1
