In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.6 MB 14.7 MB/s eta 0:00:01
   --------- ------------------------------ 3.1/12.6 MB 9.9 MB/s eta 0:00:01
   ----------- ---------------------------- 3.7/12.6 MB 6.5 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.6 MB 5.2 MB/s eta 0:00:02
   -------------- ------------------------- 4.7/12.6 MB 4.8 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 4.3 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 4.2 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 3.8 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.6 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.6 MB 3.5 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 3.6 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.6 MB 3.8 MB/s eta 0:00:01
   --


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
sales = np.array([100, 200, 150, 300, 250, 400, 350])
print(sales)

[100 200 150 300 250 400 350]


In [6]:
store1_prices = np.array([10, 20, 30])
store2_prices = np.array([1, 2, 3])
result = store1_prices * store2_prices
print(result)

[10 40 90]


In [7]:
sales_january = np.array([300, 400])
sales_february = np.array([500, 600])
combined_sales = np.concatenate((sales_january, sales_february))
print(combined_sales) 

[300 400 500 600]


In [8]:
scores = np.array([[80, 90], [85, 95]])
flat_scores = scores.flatten()
print(flat_scores)

[80 90 85 95]


In [9]:
data = np.array([1, 2, 3, 4, 5, 6])
reshaped_data = data.reshape(2, 3)
print(reshaped_data)

[[1 2 3]
 [4 5 6]]
